#include "src/component/component_system.h"
#include "src/engine/debug/debug_helper.h"
#include "src/engine/engine.h"
#include "src/entity/entity_system.h"
#include "src/input/input_system.h"
#include "src/physics/physics_system.h"
#include "src/window/window_system.h"